= api_client.model.AccountingInvoiceServiceModel

== Load the model package

[source,dart]
----
import 'package:api_client/api.dart';
----

== Properties

Name | Type | Description | Notes -------- | --------- | --------- | --------- *canSendInvoice* | *bool* |  | [optional]  *id* | *String* |  | [optional]  *fromId* | *String* |  | [optional]  *from* | xref:InvoiceParticipantServiceModel.adoc[*InvoiceParticipantServiceModel*] |  | [optional]  *toId* | *String* |  | [optional]  *to* | xref:InvoiceParticipantServiceModel.adoc[*InvoiceParticipantServiceModel*] |  | [optional]  *invoiceNumber* | *String* |  | [optional]  *referenceType* | *String* |  | [optional]  *referenceId* | *String* |  | [optional]  *total* | *double* |  | [optional]  *totalDelta* | *double* |  | [optional]  *items* | xref:InvoiceItemServiceModel.adoc[*List<InvoiceItemServiceModel>*] |  | [optional] [default to []] *reconciled* | *bool* |  | [optional]  *type* | *int* |  | [optional]  *status* | *int* |  | [optional]  *documentId* | *String* |  | [optional]

link:../README.md#documentation-for-models[[Back to Model list\]] link:../README.md#documentation-for-api-endpoints[[Back to API list\]] xref:../README.adoc[[Back to README\]]
