= api_client.api.BaseBrokerApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseBrokerApi.md#deleteBroker[*deleteBroker*]
| *POST* /deleteBroker
|

| link:BaseBrokerApi.md#getBroker[*getBroker*]
| *GET* /getBroker
|

| link:BaseBrokerApi.md#getBrokers[*getBrokers*]
| *POST* /getBrokers
|

| link:BaseBrokerApi.md#saveBroker[*saveBroker*]
| *POST* /saveBroker
|
|===

= *deleteBroker*

____
deleteBroker(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseBrokerApi();
var id = id_example; // String |

try {
    api_instance.deleteBroker(id);
} catch (e) {
    print("Exception when calling BaseBrokerApi->deleteBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getBroker*

____
BrokerServiceModel getBroker(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseBrokerApi();
var id = id_example; // String |

try {
    var result = api_instance.getBroker(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseBrokerApi->getBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:BrokerServiceModel.adoc[*BrokerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getBrokers*

____
QueryResultBrokerServiceModel getBrokers(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseBrokerApi();
var request = new BrokerQueryRequest(); // BrokerQueryRequest |

try {
    var result = api_instance.getBrokers(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseBrokerApi->getBrokers: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:BrokerQueryRequest.adoc[*BrokerQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultBrokerServiceModel.adoc[*QueryResultBrokerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveBroker*

____
BrokerServiceModel saveBroker(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseBrokerApi();
var model = new BrokerServiceModel(); // BrokerServiceModel |

try {
    var result = api_instance.saveBroker(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseBrokerApi->saveBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:BrokerServiceModel.adoc[*BrokerServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:BrokerServiceModel.adoc[*BrokerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
