= api_client.api.BaseShipmentTradingPartnerApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseShipmentTradingPartnerApi.md#deleteShipmentTradingPartner[*deleteShipmentTradingPartner*]
| *POST* /deleteShipmentTradingPartner
|

| link:BaseShipmentTradingPartnerApi.md#getShipmentTradingPartner[*getShipmentTradingPartner*]
| *GET* /getShipmentTradingPartner
|

| link:BaseShipmentTradingPartnerApi.md#getShipmentTradingPartners[*getShipmentTradingPartners*]
| *POST* /getShipmentTradingPartners
|

| link:BaseShipmentTradingPartnerApi.md#saveShipmentTradingPartner[*saveShipmentTradingPartner*]
| *POST* /saveShipmentTradingPartner
|

| link:BaseShipmentTradingPartnerApi.md#sendTender[*sendTender*]
| *POST* /sendTender
|
|===

= *deleteShipmentTradingPartner*

____
deleteShipmentTradingPartner(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentTradingPartnerApi();
var id = id_example; // String |

try {
    api_instance.deleteShipmentTradingPartner(id);
} catch (e) {
    print("Exception when calling BaseShipmentTradingPartnerApi->deleteShipmentTradingPartner: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentTradingPartner*

____
ShipmentTradingPartnerServiceModel getShipmentTradingPartner(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentTradingPartnerApi();
var id = id_example; // String |

try {
    var result = api_instance.getShipmentTradingPartner(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentTradingPartnerApi->getShipmentTradingPartner: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentTradingPartnerServiceModel.adoc[*ShipmentTradingPartnerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentTradingPartners*

____
QueryResultShipmentTradingPartnerServiceModel getShipmentTradingPartners(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentTradingPartnerApi();
var request = new ShipmentTradingPartnerQueryRequest(); // ShipmentTradingPartnerQueryRequest |

try {
    var result = api_instance.getShipmentTradingPartners(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentTradingPartnerApi->getShipmentTradingPartners: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:ShipmentTradingPartnerQueryRequest.adoc[*ShipmentTradingPartnerQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultShipmentTradingPartnerServiceModel.adoc[*QueryResultShipmentTradingPartnerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveShipmentTradingPartner*

____
ShipmentTradingPartnerServiceModel saveShipmentTradingPartner(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentTradingPartnerApi();
var model = new ShipmentTradingPartnerServiceModel(); // ShipmentTradingPartnerServiceModel |

try {
    var result = api_instance.saveShipmentTradingPartner(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentTradingPartnerApi->saveShipmentTradingPartner: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:ShipmentTradingPartnerServiceModel.adoc[*ShipmentTradingPartnerServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentTradingPartnerServiceModel.adoc[*ShipmentTradingPartnerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *sendTender*

____
ShipmentTradingPartnerServiceModel sendTender(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentTradingPartnerApi();
var request = new SendTenderRequest(); // SendTenderRequest |

try {
    var result = api_instance.sendTender(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentTradingPartnerApi->sendTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:SendTenderRequest.adoc[*SendTenderRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentTradingPartnerServiceModel.adoc[*ShipmentTradingPartnerServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
