= api_client.api.BaseCommodityTypeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseCommodityTypeApi.md#deleteCommodityType[*deleteCommodityType*]
| *POST* /deleteCommodityType
|

| link:BaseCommodityTypeApi.md#getCommodityType[*getCommodityType*]
| *GET* /getCommodityType
|

| link:BaseCommodityTypeApi.md#getCommodityTypes[*getCommodityTypes*]
| *POST* /getCommodityTypes
|

| link:BaseCommodityTypeApi.md#saveCommodityType[*saveCommodityType*]
| *POST* /saveCommodityType
|
|===

= *deleteCommodityType*

____
deleteCommodityType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseCommodityTypeApi();
var id = id_example; // String |

try {
    api_instance.deleteCommodityType(id);
} catch (e) {
    print("Exception when calling BaseCommodityTypeApi->deleteCommodityType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getCommodityType*

____
CommodityTypeServiceModel getCommodityType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseCommodityTypeApi();
var id = id_example; // String |

try {
    var result = api_instance.getCommodityType(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseCommodityTypeApi->getCommodityType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:CommodityTypeServiceModel.adoc[*CommodityTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getCommodityTypes*

____
QueryResultCommodityTypeServiceModel getCommodityTypes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseCommodityTypeApi();
var request = new CommodityTypeQueryRequest(); // CommodityTypeQueryRequest |

try {
    var result = api_instance.getCommodityTypes(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseCommodityTypeApi->getCommodityTypes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:CommodityTypeQueryRequest.adoc[*CommodityTypeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultCommodityTypeServiceModel.adoc[*QueryResultCommodityTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveCommodityType*

____
CommodityTypeServiceModel saveCommodityType(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseCommodityTypeApi();
var model = new CommodityTypeServiceModel(); // CommodityTypeServiceModel |

try {
    var result = api_instance.saveCommodityType(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseCommodityTypeApi->saveCommodityType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:CommodityTypeServiceModel.adoc[*CommodityTypeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:CommodityTypeServiceModel.adoc[*CommodityTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
