= api_client.api.BaseLadingItemApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseLadingItemApi.md#deleteLadingItem[*deleteLadingItem*]
| *POST* /deleteLadingItem
|

| link:BaseLadingItemApi.md#getLadingItem[*getLadingItem*]
| *GET* /getLadingItem
|

| link:BaseLadingItemApi.md#getLadingItems[*getLadingItems*]
| *POST* /getLadingItems
|

| link:BaseLadingItemApi.md#saveLadingItem[*saveLadingItem*]
| *POST* /saveLadingItem
|
|===

= *deleteLadingItem*

____
deleteLadingItem(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLadingItemApi();
var id = id_example; // String |

try {
    api_instance.deleteLadingItem(id);
} catch (e) {
    print("Exception when calling BaseLadingItemApi->deleteLadingItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getLadingItem*

____
LadingItemServiceModel getLadingItem(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLadingItemApi();
var id = id_example; // String |

try {
    var result = api_instance.getLadingItem(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseLadingItemApi->getLadingItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:LadingItemServiceModel.adoc[*LadingItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getLadingItems*

____
QueryResultLadingItemServiceModel getLadingItems(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLadingItemApi();
var request = new LadingItemQueryRequest(); // LadingItemQueryRequest |

try {
    var result = api_instance.getLadingItems(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseLadingItemApi->getLadingItems: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:LadingItemQueryRequest.adoc[*LadingItemQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultLadingItemServiceModel.adoc[*QueryResultLadingItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveLadingItem*

____
LadingItemServiceModel saveLadingItem(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLadingItemApi();
var model = new LadingItemServiceModel(); // LadingItemServiceModel |

try {
    var result = api_instance.saveLadingItem(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseLadingItemApi->saveLadingItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:LadingItemServiceModel.adoc[*LadingItemServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:LadingItemServiceModel.adoc[*LadingItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
