= api_client.api.BaseShipmentDeclineReasonCodeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseShipmentDeclineReasonCodeApi.md#deleteShipmentDeclineReasonCode[*deleteShipmentDeclineReasonCode*]
| *POST* /deleteShipmentDeclineReasonCode
|

| link:BaseShipmentDeclineReasonCodeApi.md#getShipmentDeclineReasonCode[*getShipmentDeclineReasonCode*]
| *GET* /getShipmentDeclineReasonCode
|

| link:BaseShipmentDeclineReasonCodeApi.md#getShipmentDeclineReasonCodes[*getShipmentDeclineReasonCodes*]
| *POST* /getShipmentDeclineReasonCodes
|

| link:BaseShipmentDeclineReasonCodeApi.md#saveShipmentDeclineReasonCode[*saveShipmentDeclineReasonCode*]
| *POST* /saveShipmentDeclineReasonCode
|
|===

= *deleteShipmentDeclineReasonCode*

____
deleteShipmentDeclineReasonCode(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentDeclineReasonCodeApi();
var id = id_example; // String |

try {
    api_instance.deleteShipmentDeclineReasonCode(id);
} catch (e) {
    print("Exception when calling BaseShipmentDeclineReasonCodeApi->deleteShipmentDeclineReasonCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentDeclineReasonCode*

____
ShipmentDeclineReasonCodeServiceModel getShipmentDeclineReasonCode(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentDeclineReasonCodeApi();
var id = id_example; // String |

try {
    var result = api_instance.getShipmentDeclineReasonCode(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentDeclineReasonCodeApi->getShipmentDeclineReasonCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentDeclineReasonCodeServiceModel.adoc[*ShipmentDeclineReasonCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentDeclineReasonCodes*

____
QueryResultShipmentDeclineReasonCodeServiceModel getShipmentDeclineReasonCodes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentDeclineReasonCodeApi();
var request = new ShipmentDeclineReasonCodeQueryRequest(); // ShipmentDeclineReasonCodeQueryRequest |

try {
    var result = api_instance.getShipmentDeclineReasonCodes(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentDeclineReasonCodeApi->getShipmentDeclineReasonCodes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:ShipmentDeclineReasonCodeQueryRequest.adoc[*ShipmentDeclineReasonCodeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultShipmentDeclineReasonCodeServiceModel.adoc[*QueryResultShipmentDeclineReasonCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveShipmentDeclineReasonCode*

____
ShipmentDeclineReasonCodeServiceModel saveShipmentDeclineReasonCode(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentDeclineReasonCodeApi();
var model = new ShipmentDeclineReasonCodeServiceModel(); // ShipmentDeclineReasonCodeServiceModel |

try {
    var result = api_instance.saveShipmentDeclineReasonCode(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentDeclineReasonCodeApi->saveShipmentDeclineReasonCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:ShipmentDeclineReasonCodeServiceModel.adoc[*ShipmentDeclineReasonCodeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentDeclineReasonCodeServiceModel.adoc[*ShipmentDeclineReasonCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
