= api_client.api.BaseEdiConfigApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseEdiConfigApi.md#deleteEdiConfig[*deleteEdiConfig*]
| *POST* /deleteEdiConfig
|

| link:BaseEdiConfigApi.md#getEdiConfig[*getEdiConfig*]
| *GET* /getEdiConfig
|

| link:BaseEdiConfigApi.md#getEdiConfigs[*getEdiConfigs*]
| *POST* /getEdiConfigs
|

| link:BaseEdiConfigApi.md#saveEdiConfig[*saveEdiConfig*]
| *POST* /saveEdiConfig
|
|===

= *deleteEdiConfig*

____
deleteEdiConfig(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiConfigApi();
var id = id_example; // String |

try {
    api_instance.deleteEdiConfig(id);
} catch (e) {
    print("Exception when calling BaseEdiConfigApi->deleteEdiConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiConfig*

____
EdiConfigServiceModel getEdiConfig(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiConfigApi();
var id = id_example; // String |

try {
    var result = api_instance.getEdiConfig(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiConfigApi->getEdiConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiConfigServiceModel.adoc[*EdiConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiConfigs*

____
QueryResultEdiConfigServiceModel getEdiConfigs(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiConfigApi();
var request = new EdiConfigQueryRequest(); // EdiConfigQueryRequest |

try {
    var result = api_instance.getEdiConfigs(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiConfigApi->getEdiConfigs: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:EdiConfigQueryRequest.adoc[*EdiConfigQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultEdiConfigServiceModel.adoc[*QueryResultEdiConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveEdiConfig*

____
EdiConfigServiceModel saveEdiConfig(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiConfigApi();
var model = new EdiConfigServiceModel(); // EdiConfigServiceModel |

try {
    var result = api_instance.saveEdiConfig(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiConfigApi->saveEdiConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:EdiConfigServiceModel.adoc[*EdiConfigServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiConfigServiceModel.adoc[*EdiConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
