= api_client.api.BaseEdiMessageLogApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseEdiMessageLogApi.md#deleteEdiMessageLog[*deleteEdiMessageLog*]
| *POST* /deleteEdiMessageLog
|

| link:BaseEdiMessageLogApi.md#getEdiMessageLog[*getEdiMessageLog*]
| *GET* /getEdiMessageLog
|

| link:BaseEdiMessageLogApi.md#getEdiMessageLogs[*getEdiMessageLogs*]
| *POST* /getEdiMessageLogs
|

| link:BaseEdiMessageLogApi.md#saveEdiMessageLog[*saveEdiMessageLog*]
| *POST* /saveEdiMessageLog
|
|===

= *deleteEdiMessageLog*

____
deleteEdiMessageLog(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiMessageLogApi();
var id = id_example; // String |

try {
    api_instance.deleteEdiMessageLog(id);
} catch (e) {
    print("Exception when calling BaseEdiMessageLogApi->deleteEdiMessageLog: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiMessageLog*

____
EdiMessageLogServiceModel getEdiMessageLog(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiMessageLogApi();
var id = id_example; // String |

try {
    var result = api_instance.getEdiMessageLog(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiMessageLogApi->getEdiMessageLog: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiMessageLogServiceModel.adoc[*EdiMessageLogServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiMessageLogs*

____
QueryResultEdiMessageLogServiceModel getEdiMessageLogs(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiMessageLogApi();
var request = new EdiMessageLogQueryRequest(); // EdiMessageLogQueryRequest |

try {
    var result = api_instance.getEdiMessageLogs(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiMessageLogApi->getEdiMessageLogs: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:EdiMessageLogQueryRequest.adoc[*EdiMessageLogQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultEdiMessageLogServiceModel.adoc[*QueryResultEdiMessageLogServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveEdiMessageLog*

____
EdiMessageLogServiceModel saveEdiMessageLog(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiMessageLogApi();
var model = new EdiMessageLogServiceModel(); // EdiMessageLogServiceModel |

try {
    var result = api_instance.saveEdiMessageLog(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiMessageLogApi->saveEdiMessageLog: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:EdiMessageLogServiceModel.adoc[*EdiMessageLogServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiMessageLogServiceModel.adoc[*EdiMessageLogServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
