= api_client.api.BaseHandlingUnitApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseHandlingUnitApi.md#deleteHandlingUnit[*deleteHandlingUnit*]
| *POST* /deleteHandlingUnit
|

| link:BaseHandlingUnitApi.md#getHandlingUnit[*getHandlingUnit*]
| *GET* /getHandlingUnit
|

| link:BaseHandlingUnitApi.md#getHandlingUnits[*getHandlingUnits*]
| *POST* /getHandlingUnits
|

| link:BaseHandlingUnitApi.md#saveHandlingUnit[*saveHandlingUnit*]
| *POST* /saveHandlingUnit
|
|===

= *deleteHandlingUnit*

____
deleteHandlingUnit(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseHandlingUnitApi();
var id = id_example; // String |

try {
    api_instance.deleteHandlingUnit(id);
} catch (e) {
    print("Exception when calling BaseHandlingUnitApi->deleteHandlingUnit: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getHandlingUnit*

____
HandlingUnitServiceModel getHandlingUnit(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseHandlingUnitApi();
var id = id_example; // String |

try {
    var result = api_instance.getHandlingUnit(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseHandlingUnitApi->getHandlingUnit: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:HandlingUnitServiceModel.adoc[*HandlingUnitServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getHandlingUnits*

____
QueryResultHandlingUnitServiceModel getHandlingUnits(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseHandlingUnitApi();
var request = new HandlingUnitQueryRequest(); // HandlingUnitQueryRequest |

try {
    var result = api_instance.getHandlingUnits(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseHandlingUnitApi->getHandlingUnits: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:HandlingUnitQueryRequest.adoc[*HandlingUnitQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultHandlingUnitServiceModel.adoc[*QueryResultHandlingUnitServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveHandlingUnit*

____
HandlingUnitServiceModel saveHandlingUnit(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseHandlingUnitApi();
var model = new HandlingUnitServiceModel(); // HandlingUnitServiceModel |

try {
    var result = api_instance.saveHandlingUnit(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseHandlingUnitApi->saveHandlingUnit: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:HandlingUnitServiceModel.adoc[*HandlingUnitServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:HandlingUnitServiceModel.adoc[*HandlingUnitServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
