= api_client.api.BaseTradingChannelApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseTradingChannelApi.md#deleteTradingChannel[*deleteTradingChannel*]
| *POST* /deleteTradingChannel
|

| link:BaseTradingChannelApi.md#generateKeys[*generateKeys*]
| *POST* /generateKeys
|

| link:BaseTradingChannelApi.md#getTradingChannel[*getTradingChannel*]
| *GET* /getTradingChannel
|

| link:BaseTradingChannelApi.md#getTradingChannels[*getTradingChannels*]
| *POST* /getTradingChannels
|

| link:BaseTradingChannelApi.md#saveTradingChannel[*saveTradingChannel*]
| *POST* /saveTradingChannel
|
|===

= *deleteTradingChannel*

____
deleteTradingChannel(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTradingChannelApi();
var id = id_example; // String |

try {
    api_instance.deleteTradingChannel(id);
} catch (e) {
    print("Exception when calling BaseTradingChannelApi->deleteTradingChannel: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *generateKeys*

____
TradingChannelServiceModel generateKeys(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTradingChannelApi();
var request = new GenerateKeysRequest(); // GenerateKeysRequest |

try {
    var result = api_instance.generateKeys(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseTradingChannelApi->generateKeys: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:GenerateKeysRequest.adoc[*GenerateKeysRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:TradingChannelServiceModel.adoc[*TradingChannelServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getTradingChannel*

____
TradingChannelServiceModel getTradingChannel(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTradingChannelApi();
var id = id_example; // String |

try {
    var result = api_instance.getTradingChannel(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseTradingChannelApi->getTradingChannel: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:TradingChannelServiceModel.adoc[*TradingChannelServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getTradingChannels*

____
QueryResultTradingChannelServiceModel getTradingChannels(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTradingChannelApi();
var request = new TradingChannelQueryRequest(); // TradingChannelQueryRequest |

try {
    var result = api_instance.getTradingChannels(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseTradingChannelApi->getTradingChannels: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:TradingChannelQueryRequest.adoc[*TradingChannelQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultTradingChannelServiceModel.adoc[*QueryResultTradingChannelServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveTradingChannel*

____
TradingChannelServiceModel saveTradingChannel(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTradingChannelApi();
var model = new TradingChannelServiceModel(); // TradingChannelServiceModel |

try {
    var result = api_instance.saveTradingChannel(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseTradingChannelApi->saveTradingChannel: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:TradingChannelServiceModel.adoc[*TradingChannelServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:TradingChannelServiceModel.adoc[*TradingChannelServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
