= api_client.api.BaseStopUpdateApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseStopUpdateApi.md#deleteStopUpdate[*deleteStopUpdate*]
| *POST* /deleteStopUpdate
|

| link:BaseStopUpdateApi.md#getStopUpdate[*getStopUpdate*]
| *GET* /getStopUpdate
|

| link:BaseStopUpdateApi.md#getStopUpdates[*getStopUpdates*]
| *POST* /getStopUpdates
|

| link:BaseStopUpdateApi.md#saveStopUpdate[*saveStopUpdate*]
| *POST* /saveStopUpdate
|
|===

= *deleteStopUpdate*

____
deleteStopUpdate(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopUpdateApi();
var id = id_example; // String |

try {
    api_instance.deleteStopUpdate(id);
} catch (e) {
    print("Exception when calling BaseStopUpdateApi->deleteStopUpdate: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getStopUpdate*

____
StopUpdateServiceModel getStopUpdate(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopUpdateApi();
var id = id_example; // String |

try {
    var result = api_instance.getStopUpdate(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopUpdateApi->getStopUpdate: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:StopUpdateServiceModel.adoc[*StopUpdateServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getStopUpdates*

____
QueryResultStopUpdateServiceModel getStopUpdates(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopUpdateApi();
var request = new StopUpdateQueryRequest(); // StopUpdateQueryRequest |

try {
    var result = api_instance.getStopUpdates(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopUpdateApi->getStopUpdates: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:StopUpdateQueryRequest.adoc[*StopUpdateQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultStopUpdateServiceModel.adoc[*QueryResultStopUpdateServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveStopUpdate*

____
StopUpdateServiceModel saveStopUpdate(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopUpdateApi();
var model = new StopUpdateServiceModel(); // StopUpdateServiceModel |

try {
    var result = api_instance.saveStopUpdate(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopUpdateApi->saveStopUpdate: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:StopUpdateServiceModel.adoc[*StopUpdateServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:StopUpdateServiceModel.adoc[*StopUpdateServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
