= api_client.api.BaseSamsaraConfigApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseSamsaraConfigApi.md#getSamsaraConfig[*getSamsaraConfig*]
| *GET* /getSamsaraConfig
|

| link:BaseSamsaraConfigApi.md#saveSamsaraConfig[*saveSamsaraConfig*]
| *POST* /saveSamsaraConfig
|
|===

= *getSamsaraConfig*

____
SamsaraConfigServiceModel getSamsaraConfig(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSamsaraConfigApi();
var id = id_example; // String |

try {
    var result = api_instance.getSamsaraConfig(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseSamsaraConfigApi->getSamsaraConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:SamsaraConfigServiceModel.adoc[*SamsaraConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveSamsaraConfig*

____
SamsaraConfigServiceModel saveSamsaraConfig(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSamsaraConfigApi();
var model = new SamsaraConfigServiceModel(); // SamsaraConfigServiceModel |

try {
    var result = api_instance.saveSamsaraConfig(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseSamsaraConfigApi->saveSamsaraConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:SamsaraConfigServiceModel.adoc[*SamsaraConfigServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:SamsaraConfigServiceModel.adoc[*SamsaraConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
