= api_client.api.BaseShipmentAppointmentStatusCodeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseShipmentAppointmentStatusCodeApi.md#deleteShipmentAppointmentStatusCode[*deleteShipmentAppointmentStatusCode*]
| *POST* /deleteShipmentAppointmentStatusCode
|

| link:BaseShipmentAppointmentStatusCodeApi.md#getShipmentAppointmentStatusCode[*getShipmentAppointmentStatusCode*]
| *GET* /getShipmentAppointmentStatusCode
|

| link:BaseShipmentAppointmentStatusCodeApi.md#getShipmentAppointmentStatusCodes[*getShipmentAppointmentStatusCodes*]
| *POST* /getShipmentAppointmentStatusCodes
|

| link:BaseShipmentAppointmentStatusCodeApi.md#saveShipmentAppointmentStatusCode[*saveShipmentAppointmentStatusCode*]
| *POST* /saveShipmentAppointmentStatusCode
|
|===

= *deleteShipmentAppointmentStatusCode*

____
deleteShipmentAppointmentStatusCode(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentAppointmentStatusCodeApi();
var id = id_example; // String |

try {
    api_instance.deleteShipmentAppointmentStatusCode(id);
} catch (e) {
    print("Exception when calling BaseShipmentAppointmentStatusCodeApi->deleteShipmentAppointmentStatusCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentAppointmentStatusCode*

____
ShipmentAppointmentStatusCodeServiceModel getShipmentAppointmentStatusCode(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentAppointmentStatusCodeApi();
var id = id_example; // String |

try {
    var result = api_instance.getShipmentAppointmentStatusCode(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentAppointmentStatusCodeApi->getShipmentAppointmentStatusCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentAppointmentStatusCodeServiceModel.adoc[*ShipmentAppointmentStatusCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getShipmentAppointmentStatusCodes*

____
QueryResultShipmentAppointmentStatusCodeServiceModel getShipmentAppointmentStatusCodes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentAppointmentStatusCodeApi();
var request = new ShipmentAppointmentStatusCodeQueryRequest(); // ShipmentAppointmentStatusCodeQueryRequest |

try {
    var result = api_instance.getShipmentAppointmentStatusCodes(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentAppointmentStatusCodeApi->getShipmentAppointmentStatusCodes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:ShipmentAppointmentStatusCodeQueryRequest.adoc[*ShipmentAppointmentStatusCodeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultShipmentAppointmentStatusCodeServiceModel.adoc[*QueryResultShipmentAppointmentStatusCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveShipmentAppointmentStatusCode*

____
ShipmentAppointmentStatusCodeServiceModel saveShipmentAppointmentStatusCode(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentAppointmentStatusCodeApi();
var model = new ShipmentAppointmentStatusCodeServiceModel(); // ShipmentAppointmentStatusCodeServiceModel |

try {
    var result = api_instance.saveShipmentAppointmentStatusCode(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentAppointmentStatusCodeApi->saveShipmentAppointmentStatusCode: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:ShipmentAppointmentStatusCodeServiceModel.adoc[*ShipmentAppointmentStatusCodeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentAppointmentStatusCodeServiceModel.adoc[*ShipmentAppointmentStatusCodeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
