= api_client.api.BaseNmfcClassApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseNmfcClassApi.md#deleteNmfcClass[*deleteNmfcClass*]
| *POST* /deleteNmfcClass
|

| link:BaseNmfcClassApi.md#getNmfcClass[*getNmfcClass*]
| *GET* /getNmfcClass
|

| link:BaseNmfcClassApi.md#getNmfcClasses[*getNmfcClasses*]
| *POST* /getNmfcClasses
|

| link:BaseNmfcClassApi.md#saveNmfcClass[*saveNmfcClass*]
| *POST* /saveNmfcClass
|
|===

= *deleteNmfcClass*

____
deleteNmfcClass(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseNmfcClassApi();
var id = id_example; // String |

try {
    api_instance.deleteNmfcClass(id);
} catch (e) {
    print("Exception when calling BaseNmfcClassApi->deleteNmfcClass: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getNmfcClass*

____
NmfcClassServiceModel getNmfcClass(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseNmfcClassApi();
var id = id_example; // String |

try {
    var result = api_instance.getNmfcClass(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseNmfcClassApi->getNmfcClass: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:NmfcClassServiceModel.adoc[*NmfcClassServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getNmfcClasses*

____
QueryResultNmfcClassServiceModel getNmfcClasses(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseNmfcClassApi();
var request = new NmfcClassQueryRequest(); // NmfcClassQueryRequest |

try {
    var result = api_instance.getNmfcClasses(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseNmfcClassApi->getNmfcClasses: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:NmfcClassQueryRequest.adoc[*NmfcClassQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultNmfcClassServiceModel.adoc[*QueryResultNmfcClassServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveNmfcClass*

____
NmfcClassServiceModel saveNmfcClass(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseNmfcClassApi();
var model = new NmfcClassServiceModel(); // NmfcClassServiceModel |

try {
    var result = api_instance.saveNmfcClass(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseNmfcClassApi->saveNmfcClass: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:NmfcClassServiceModel.adoc[*NmfcClassServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:NmfcClassServiceModel.adoc[*NmfcClassServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
