= api_client.api.BaseRoleClaimApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseRoleClaimApi.md#deleteRoleClaim[*deleteRoleClaim*]
| *POST* /deleteRoleClaim
|

| link:BaseRoleClaimApi.md#getRoleClaim[*getRoleClaim*]
| *GET* /getRoleClaim
|

| link:BaseRoleClaimApi.md#getRoleClaims[*getRoleClaims*]
| *POST* /getRoleClaims
|

| link:BaseRoleClaimApi.md#saveRoleClaim[*saveRoleClaim*]
| *POST* /saveRoleClaim
|
|===

= *deleteRoleClaim*

____
deleteRoleClaim(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseRoleClaimApi();
var id = id_example; // String |

try {
    api_instance.deleteRoleClaim(id);
} catch (e) {
    print("Exception when calling BaseRoleClaimApi->deleteRoleClaim: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getRoleClaim*

____
RoleClaimServiceModel getRoleClaim(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseRoleClaimApi();
var id = id_example; // String |

try {
    var result = api_instance.getRoleClaim(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseRoleClaimApi->getRoleClaim: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:RoleClaimServiceModel.adoc[*RoleClaimServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getRoleClaims*

____
QueryResultRoleClaimServiceModel getRoleClaims(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseRoleClaimApi();
var request = new RoleClaimQueryRequest(); // RoleClaimQueryRequest |

try {
    var result = api_instance.getRoleClaims(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseRoleClaimApi->getRoleClaims: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:RoleClaimQueryRequest.adoc[*RoleClaimQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultRoleClaimServiceModel.adoc[*QueryResultRoleClaimServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveRoleClaim*

____
RoleClaimServiceModel saveRoleClaim(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseRoleClaimApi();
var model = new RoleClaimServiceModel(); // RoleClaimServiceModel |

try {
    var result = api_instance.saveRoleClaim(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseRoleClaimApi->saveRoleClaim: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:RoleClaimServiceModel.adoc[*RoleClaimServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:RoleClaimServiceModel.adoc[*RoleClaimServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
