= api_client.api.BaseInvoiceItemApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseInvoiceItemApi.md#deleteInvoiceItem[*deleteInvoiceItem*]
| *POST* /deleteInvoiceItem
|

| link:BaseInvoiceItemApi.md#getInvoiceItem[*getInvoiceItem*]
| *GET* /getInvoiceItem
|

| link:BaseInvoiceItemApi.md#getInvoiceItems[*getInvoiceItems*]
| *POST* /getInvoiceItems
|

| link:BaseInvoiceItemApi.md#saveInvoiceItem[*saveInvoiceItem*]
| *POST* /saveInvoiceItem
|
|===

= *deleteInvoiceItem*

____
deleteInvoiceItem(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseInvoiceItemApi();
var id = id_example; // String |

try {
    api_instance.deleteInvoiceItem(id);
} catch (e) {
    print("Exception when calling BaseInvoiceItemApi->deleteInvoiceItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getInvoiceItem*

____
InvoiceItemServiceModel getInvoiceItem(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseInvoiceItemApi();
var id = id_example; // String |

try {
    var result = api_instance.getInvoiceItem(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseInvoiceItemApi->getInvoiceItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:InvoiceItemServiceModel.adoc[*InvoiceItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getInvoiceItems*

____
QueryResultInvoiceItemServiceModel getInvoiceItems(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseInvoiceItemApi();
var request = new InvoiceItemQueryRequest(); // InvoiceItemQueryRequest |

try {
    var result = api_instance.getInvoiceItems(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseInvoiceItemApi->getInvoiceItems: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:InvoiceItemQueryRequest.adoc[*InvoiceItemQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultInvoiceItemServiceModel.adoc[*QueryResultInvoiceItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveInvoiceItem*

____
InvoiceItemServiceModel saveInvoiceItem(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseInvoiceItemApi();
var model = new InvoiceItemServiceModel(); // InvoiceItemServiceModel |

try {
    var result = api_instance.saveInvoiceItem(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseInvoiceItemApi->saveInvoiceItem: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:InvoiceItemServiceModel.adoc[*InvoiceItemServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:InvoiceItemServiceModel.adoc[*InvoiceItemServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
