= api_client.api.BaseSaferCarrierApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseSaferCarrierApi.md#deleteSaferCarrier[*deleteSaferCarrier*]
| *POST* /deleteSaferCarrier
|

| link:BaseSaferCarrierApi.md#getSaferCarrier[*getSaferCarrier*]
| *GET* /getSaferCarrier
|

| link:BaseSaferCarrierApi.md#getSaferCarriers[*getSaferCarriers*]
| *POST* /getSaferCarriers
|

| link:BaseSaferCarrierApi.md#saveSaferCarrier[*saveSaferCarrier*]
| *POST* /saveSaferCarrier
|
|===

= *deleteSaferCarrier*

____
deleteSaferCarrier(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSaferCarrierApi();
var id = id_example; // String |

try {
    api_instance.deleteSaferCarrier(id);
} catch (e) {
    print("Exception when calling BaseSaferCarrierApi->deleteSaferCarrier: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getSaferCarrier*

____
SaferCarrierServiceModel getSaferCarrier(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSaferCarrierApi();
var id = id_example; // String |

try {
    var result = api_instance.getSaferCarrier(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseSaferCarrierApi->getSaferCarrier: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:SaferCarrierServiceModel.adoc[*SaferCarrierServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getSaferCarriers*

____
QueryResultSaferCarrierServiceModel getSaferCarriers(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSaferCarrierApi();
var request = new SaferCarrierQueryRequest(); // SaferCarrierQueryRequest |

try {
    var result = api_instance.getSaferCarriers(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseSaferCarrierApi->getSaferCarriers: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:SaferCarrierQueryRequest.adoc[*SaferCarrierQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultSaferCarrierServiceModel.adoc[*QueryResultSaferCarrierServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveSaferCarrier*

____
SaferCarrierServiceModel saveSaferCarrier(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseSaferCarrierApi();
var model = new SaferCarrierServiceModel(); // SaferCarrierServiceModel |

try {
    var result = api_instance.saveSaferCarrier(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseSaferCarrierApi->saveSaferCarrier: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:SaferCarrierServiceModel.adoc[*SaferCarrierServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:SaferCarrierServiceModel.adoc[*SaferCarrierServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
