= api_client.api.BaseOrderItemReferenceNumberTypeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseOrderItemReferenceNumberTypeApi.md#deleteOrderItemReferenceNumberType[*deleteOrderItemReferenceNumberType*]
| *POST* /deleteOrderItemReferenceNumberType
|

| link:BaseOrderItemReferenceNumberTypeApi.md#getOrderItemReferenceNumberType[*getOrderItemReferenceNumberType*]
| *GET* /getOrderItemReferenceNumberType
|

| link:BaseOrderItemReferenceNumberTypeApi.md#getOrderItemReferenceNumberTypes[*getOrderItemReferenceNumberTypes*]
| *POST* /getOrderItemReferenceNumberTypes
|

| link:BaseOrderItemReferenceNumberTypeApi.md#saveOrderItemReferenceNumberType[*saveOrderItemReferenceNumberType*]
| *POST* /saveOrderItemReferenceNumberType
|
|===

= *deleteOrderItemReferenceNumberType*

____
deleteOrderItemReferenceNumberType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseOrderItemReferenceNumberTypeApi();
var id = id_example; // String |

try {
    api_instance.deleteOrderItemReferenceNumberType(id);
} catch (e) {
    print("Exception when calling BaseOrderItemReferenceNumberTypeApi->deleteOrderItemReferenceNumberType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getOrderItemReferenceNumberType*

____
OrderItemReferenceNumberTypeServiceModel getOrderItemReferenceNumberType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseOrderItemReferenceNumberTypeApi();
var id = id_example; // String |

try {
    var result = api_instance.getOrderItemReferenceNumberType(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseOrderItemReferenceNumberTypeApi->getOrderItemReferenceNumberType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:OrderItemReferenceNumberTypeServiceModel.adoc[*OrderItemReferenceNumberTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getOrderItemReferenceNumberTypes*

____
QueryResultOrderItemReferenceNumberTypeServiceModel getOrderItemReferenceNumberTypes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseOrderItemReferenceNumberTypeApi();
var request = new OrderItemReferenceNumberTypeQueryRequest(); // OrderItemReferenceNumberTypeQueryRequest |

try {
    var result = api_instance.getOrderItemReferenceNumberTypes(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseOrderItemReferenceNumberTypeApi->getOrderItemReferenceNumberTypes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:OrderItemReferenceNumberTypeQueryRequest.adoc[*OrderItemReferenceNumberTypeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultOrderItemReferenceNumberTypeServiceModel.adoc[*QueryResultOrderItemReferenceNumberTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveOrderItemReferenceNumberType*

____
OrderItemReferenceNumberTypeServiceModel saveOrderItemReferenceNumberType(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseOrderItemReferenceNumberTypeApi();
var model = new OrderItemReferenceNumberTypeServiceModel(); // OrderItemReferenceNumberTypeServiceModel |

try {
    var result = api_instance.saveOrderItemReferenceNumberType(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseOrderItemReferenceNumberTypeApi->saveOrderItemReferenceNumberType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:OrderItemReferenceNumberTypeServiceModel.adoc[*OrderItemReferenceNumberTypeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:OrderItemReferenceNumberTypeServiceModel.adoc[*OrderItemReferenceNumberTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
