= api_client.api.BasePermissionApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BasePermissionApi.md#deletePermission[*deletePermission*]
| *POST* /deletePermission
|

| link:BasePermissionApi.md#getPermission[*getPermission*]
| *GET* /getPermission
|

| link:BasePermissionApi.md#getPermissions[*getPermissions*]
| *POST* /getPermissions
|

| link:BasePermissionApi.md#savePermission[*savePermission*]
| *POST* /savePermission
|
|===

= *deletePermission*

____
deletePermission(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePermissionApi();
var id = id_example; // String |

try {
    api_instance.deletePermission(id);
} catch (e) {
    print("Exception when calling BasePermissionApi->deletePermission: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getPermission*

____
PermissionServiceModel getPermission(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePermissionApi();
var id = id_example; // String |

try {
    var result = api_instance.getPermission(id);
    print(result);
} catch (e) {
    print("Exception when calling BasePermissionApi->getPermission: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:PermissionServiceModel.adoc[*PermissionServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getPermissions*

____
QueryResultPermissionServiceModel getPermissions(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePermissionApi();
var request = new PermissionQueryRequest(); // PermissionQueryRequest |

try {
    var result = api_instance.getPermissions(request);
    print(result);
} catch (e) {
    print("Exception when calling BasePermissionApi->getPermissions: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:PermissionQueryRequest.adoc[*PermissionQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultPermissionServiceModel.adoc[*QueryResultPermissionServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *savePermission*

____
PermissionServiceModel savePermission(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePermissionApi();
var model = new PermissionServiceModel(); // PermissionServiceModel |

try {
    var result = api_instance.savePermission(model);
    print(result);
} catch (e) {
    print("Exception when calling BasePermissionApi->savePermission: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:PermissionServiceModel.adoc[*PermissionServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:PermissionServiceModel.adoc[*PermissionServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
