= api_client.api.BaseStopApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseStopApi.md#deleteStop[*deleteStop*]
| *POST* /deleteStop
|

| link:BaseStopApi.md#getStop[*getStop*]
| *GET* /getStop
|

| link:BaseStopApi.md#getStops[*getStops*]
| *POST* /getStops
|

| link:BaseStopApi.md#saveStop[*saveStop*]
| *POST* /saveStop
|

| link:BaseStopApi.md#stopStatusUpdate[*stopStatusUpdate*]
| *POST* /stopStatusUpdate
|
|===

= *deleteStop*

____
deleteStop(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopApi();
var id = id_example; // String |

try {
    api_instance.deleteStop(id);
} catch (e) {
    print("Exception when calling BaseStopApi->deleteStop: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getStop*

____
StopServiceModel getStop(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopApi();
var id = id_example; // String |

try {
    var result = api_instance.getStop(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopApi->getStop: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:StopServiceModel.adoc[*StopServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getStops*

____
QueryResultStopServiceModel getStops(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopApi();
var request = new StopQueryRequest(); // StopQueryRequest |

try {
    var result = api_instance.getStops(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopApi->getStops: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:StopQueryRequest.adoc[*StopQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultStopServiceModel.adoc[*QueryResultStopServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveStop*

____
StopServiceModel saveStop(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopApi();
var model = new StopServiceModel(); // StopServiceModel |

try {
    var result = api_instance.saveStop(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopApi->saveStop: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:StopServiceModel.adoc[*StopServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:StopServiceModel.adoc[*StopServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *stopStatusUpdate*

____
StopServiceModel stopStatusUpdate(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseStopApi();
var request = new StopStatusUpdateRequest(); // StopStatusUpdateRequest |

try {
    var result = api_instance.stopStatusUpdate(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseStopApi->stopStatusUpdate: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:StopStatusUpdateRequest.adoc[*StopStatusUpdateRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:StopServiceModel.adoc[*StopServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
