= api_client.api.BaseTenderApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseTenderApi.md#deleteTender[*deleteTender*]
| *POST* /deleteTender
|

| link:BaseTenderApi.md#getTender[*getTender*]
| *GET* /getTender
|

| link:BaseTenderApi.md#getTenders[*getTenders*]
| *POST* /getTenders
|

| link:BaseTenderApi.md#saveTender[*saveTender*]
| *POST* /saveTender
|
|===

= *deleteTender*

____
deleteTender(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTenderApi();
var id = id_example; // String |

try {
    api_instance.deleteTender(id);
} catch (e) {
    print("Exception when calling BaseTenderApi->deleteTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getTender*

____
TenderServiceModel getTender(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTenderApi();
var id = id_example; // String |

try {
    var result = api_instance.getTender(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseTenderApi->getTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:TenderServiceModel.adoc[*TenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getTenders*

____
QueryResultTenderServiceModel getTenders(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTenderApi();
var request = new TenderQueryRequest(); // TenderQueryRequest |

try {
    var result = api_instance.getTenders(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseTenderApi->getTenders: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:TenderQueryRequest.adoc[*TenderQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultTenderServiceModel.adoc[*QueryResultTenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveTender*

____
TenderServiceModel saveTender(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseTenderApi();
var model = new TenderServiceModel(); // TenderServiceModel |

try {
    var result = api_instance.saveTender(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseTenderApi->saveTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:TenderServiceModel.adoc[*TenderServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:TenderServiceModel.adoc[*TenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
