= api_client.api.BaseLoadSizeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseLoadSizeApi.md#deleteLoadSize[*deleteLoadSize*]
| *POST* /deleteLoadSize
|

| link:BaseLoadSizeApi.md#getLoadSize[*getLoadSize*]
| *GET* /getLoadSize
|

| link:BaseLoadSizeApi.md#getLoadSizes[*getLoadSizes*]
| *POST* /getLoadSizes
|

| link:BaseLoadSizeApi.md#saveLoadSize[*saveLoadSize*]
| *POST* /saveLoadSize
|
|===

= *deleteLoadSize*

____
deleteLoadSize(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLoadSizeApi();
var id = id_example; // String |

try {
    api_instance.deleteLoadSize(id);
} catch (e) {
    print("Exception when calling BaseLoadSizeApi->deleteLoadSize: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getLoadSize*

____
LoadSizeServiceModel getLoadSize(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLoadSizeApi();
var id = id_example; // String |

try {
    var result = api_instance.getLoadSize(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseLoadSizeApi->getLoadSize: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:LoadSizeServiceModel.adoc[*LoadSizeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getLoadSizes*

____
QueryResultLoadSizeServiceModel getLoadSizes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLoadSizeApi();
var request = new LoadSizeQueryRequest(); // LoadSizeQueryRequest |

try {
    var result = api_instance.getLoadSizes(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseLoadSizeApi->getLoadSizes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:LoadSizeQueryRequest.adoc[*LoadSizeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultLoadSizeServiceModel.adoc[*QueryResultLoadSizeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveLoadSize*

____
LoadSizeServiceModel saveLoadSize(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseLoadSizeApi();
var model = new LoadSizeServiceModel(); // LoadSizeServiceModel |

try {
    var result = api_instance.saveLoadSize(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseLoadSizeApi->saveLoadSize: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:LoadSizeServiceModel.adoc[*LoadSizeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:LoadSizeServiceModel.adoc[*LoadSizeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
