= api_client.api.BaseEdiTenderApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseEdiTenderApi.md#deleteEdiTender[*deleteEdiTender*]
| *POST* /deleteEdiTender
|

| link:BaseEdiTenderApi.md#getEdiTender[*getEdiTender*]
| *GET* /getEdiTender
|

| link:BaseEdiTenderApi.md#getEdiTenders[*getEdiTenders*]
| *POST* /getEdiTenders
|

| link:BaseEdiTenderApi.md#saveEdiTender[*saveEdiTender*]
| *POST* /saveEdiTender
|
|===

= *deleteEdiTender*

____
deleteEdiTender(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiTenderApi();
var id = id_example; // String |

try {
    api_instance.deleteEdiTender(id);
} catch (e) {
    print("Exception when calling BaseEdiTenderApi->deleteEdiTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiTender*

____
EdiTenderServiceModel getEdiTender(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiTenderApi();
var id = id_example; // String |

try {
    var result = api_instance.getEdiTender(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiTenderApi->getEdiTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiTenderServiceModel.adoc[*EdiTenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getEdiTenders*

____
QueryResultEdiTenderServiceModel getEdiTenders(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiTenderApi();
var request = new EdiTenderQueryRequest(); // EdiTenderQueryRequest |

try {
    var result = api_instance.getEdiTenders(request);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiTenderApi->getEdiTenders: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:EdiTenderQueryRequest.adoc[*EdiTenderQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultEdiTenderServiceModel.adoc[*QueryResultEdiTenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveEdiTender*

____
EdiTenderServiceModel saveEdiTender(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseEdiTenderApi();
var model = new EdiTenderServiceModel(); // EdiTenderServiceModel |

try {
    var result = api_instance.saveEdiTender(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseEdiTenderApi->saveEdiTender: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:EdiTenderServiceModel.adoc[*EdiTenderServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:EdiTenderServiceModel.adoc[*EdiTenderServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
