= api_client.api.BasePackageTypeApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BasePackageTypeApi.md#deletePackageType[*deletePackageType*]
| *POST* /deletePackageType
|

| link:BasePackageTypeApi.md#getPackageType[*getPackageType*]
| *GET* /getPackageType
|

| link:BasePackageTypeApi.md#getPackageTypes[*getPackageTypes*]
| *POST* /getPackageTypes
|

| link:BasePackageTypeApi.md#savePackageType[*savePackageType*]
| *POST* /savePackageType
|
|===

= *deletePackageType*

____
deletePackageType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePackageTypeApi();
var id = id_example; // String |

try {
    api_instance.deletePackageType(id);
} catch (e) {
    print("Exception when calling BasePackageTypeApi->deletePackageType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getPackageType*

____
PackageTypeServiceModel getPackageType(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePackageTypeApi();
var id = id_example; // String |

try {
    var result = api_instance.getPackageType(id);
    print(result);
} catch (e) {
    print("Exception when calling BasePackageTypeApi->getPackageType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:PackageTypeServiceModel.adoc[*PackageTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getPackageTypes*

____
QueryResultPackageTypeServiceModel getPackageTypes(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePackageTypeApi();
var request = new PackageTypeQueryRequest(); // PackageTypeQueryRequest |

try {
    var result = api_instance.getPackageTypes(request);
    print(result);
} catch (e) {
    print("Exception when calling BasePackageTypeApi->getPackageTypes: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:PackageTypeQueryRequest.adoc[*PackageTypeQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultPackageTypeServiceModel.adoc[*QueryResultPackageTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *savePackageType*

____
PackageTypeServiceModel savePackageType(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BasePackageTypeApi();
var model = new PackageTypeServiceModel(); // PackageTypeServiceModel |

try {
    var result = api_instance.savePackageType(model);
    print(result);
} catch (e) {
    print("Exception when calling BasePackageTypeApi->savePackageType: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:PackageTypeServiceModel.adoc[*PackageTypeServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:PackageTypeServiceModel.adoc[*PackageTypeServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
