= api_client.api.BaseShipmentConfigApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BaseShipmentConfigApi.md#getShipmentConfig[*getShipmentConfig*]
| *GET* /getShipmentConfig
|

| link:BaseShipmentConfigApi.md#saveShipmentConfig[*saveShipmentConfig*]
| *POST* /saveShipmentConfig
|
|===

= *getShipmentConfig*

____
ShipmentConfigServiceModel getShipmentConfig(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentConfigApi();
var id = id_example; // String |

try {
    var result = api_instance.getShipmentConfig(id);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentConfigApi->getShipmentConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentConfigServiceModel.adoc[*ShipmentConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveShipmentConfig*

____
ShipmentConfigServiceModel saveShipmentConfig(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new BaseShipmentConfigApi();
var model = new ShipmentConfigServiceModel(); // ShipmentConfigServiceModel |

try {
    var result = api_instance.saveShipmentConfig(model);
    print(result);
} catch (e) {
    print("Exception when calling BaseShipmentConfigApi->saveShipmentConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:ShipmentConfigServiceModel.adoc[*ShipmentConfigServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentConfigServiceModel.adoc[*ShipmentConfigServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
