= api_client.model.BrokerCarrierQuoteServiceModel

== Load the model package

[source,dart]
----
import 'package:api_client/api.dart';
----

== Properties

Name | Type | Description | Notes -------- | --------- | --------- | --------- *carrierCompany* | xref:CompanyServiceModel.adoc[*CompanyServiceModel*] |  | [optional]  *quotePrice* | *double* |  | [optional]  *status* | *int* |  | [optional]  *terms* | *int* |  | [optional]  *requestedTimestamp* | xref:DateTime.adoc[*DateTime*] |  | [optional]  *responseTimestamp* | xref:DateTime.adoc[*DateTime*] |  | [optional]  *additionalInformation* | xref:CarrierAdditionalInfoServiceModel.adoc[*CarrierAdditionalInfoServiceModel*] |  | [optional]  *carrierQuoteRequestId* | *String* |  | [optional]  *isSubscribed* | *bool* |  | [optional]  *deliveryWindowProbability* | *int* |  | [optional]  *routeProximity* | *int* |  | [optional]  *numberOfDeliveriesToLocation* | *int* |  | [optional]  *incidentsLast30Days* | *int* |  | [optional]

link:../README.md#documentation-for-models[[Back to Model list\]] link:../README.md#documentation-for-api-endpoints[[Back to API list\]] xref:../README.adoc[[Back to README\]]
