= api_client.api.BrokerApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:BrokerApi.md#deleteBroker[*deleteBroker*]
| *POST* /api/Broker/deleteBroker
|

| link:BrokerApi.md#getBroker[*getBroker*]
| *GET* /api/Broker/getBroker
|

| link:BrokerApi.md#getBrokers[*getBrokers*]
| *POST* /api/Broker/getBrokers
|

| link:BrokerApi.md#saveBroker[*saveBroker*]
| *POST* /api/Broker/saveBroker
|
|===

= *deleteBroker*

____
deleteBroker(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new BrokerApi();
var id = id_example; // String |

try {
    api_instance.deleteBroker(id);
} catch (e) {
    print("Exception when calling BrokerApi->deleteBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

void (empty response body)

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getBroker*

____
BrokerServiceModel getBroker(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new BrokerApi();
var id = id_example; // String |

try {
    var result = api_instance.getBroker(id);
    print(result);
} catch (e) {
    print("Exception when calling BrokerApi->getBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:BrokerServiceModel.adoc[*BrokerServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getBrokers*

____
QueryResultBrokerServiceModel getBrokers(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new BrokerApi();
var request = new BrokerQueryRequest(); // BrokerQueryRequest |

try {
    var result = api_instance.getBrokers(request);
    print(result);
} catch (e) {
    print("Exception when calling BrokerApi->getBrokers: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:BrokerQueryRequest.adoc[*BrokerQueryRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultBrokerServiceModel.adoc[*QueryResultBrokerServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveBroker*

____
BrokerServiceModel saveBroker(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new BrokerApi();
var model = new BrokerServiceModel(); // BrokerServiceModel |

try {
    var result = api_instance.saveBroker(model);
    print(result);
} catch (e) {
    print("Exception when calling BrokerApi->saveBroker: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:BrokerServiceModel.adoc[*BrokerServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:BrokerServiceModel.adoc[*BrokerServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
