= api_client.model.CarrierQuoteRequestServiceModel

== Load the model package

[source,dart]
----
import 'package:api_client/api.dart';
----

== Properties

Name | Type | Description | Notes -------- | --------- | --------- | --------- *id* | *String* |  | [optional]  *shipmentId* | *String* |  | [optional]  *quotePrice* | *double* |  | [optional]  *status* | *int* |  | [optional]  *requestedTimestamp* | xref:DateTime.adoc[*DateTime*] |  | [optional]  *responseTimestamp* | xref:DateTime.adoc[*DateTime*] |  | [optional]  *companyId* | *String* |  | [optional]  *shipperCompany* | xref:CompanyServiceModel.adoc[*CompanyServiceModel*] |  | [optional]  *auditTrail* | xref:AuditTrailServiceModel.adoc[*List<AuditTrailServiceModel>*] |  | [optional] [default to []] *terms* | *int* |  | [optional]  *createdBy* | xref:UserServiceModel.adoc[*UserServiceModel*] |  | [optional]  *lastModifiedBy* | xref:UserServiceModel.adoc[*UserServiceModel*] |  | [optional]  *additionalInformation* | xref:CarrierAdditionalInfoServiceModel.adoc[*CarrierAdditionalInfoServiceModel*] |  | [optional]  *brokerCompany* | xref:CompanyServiceModel.adoc[*CompanyServiceModel*] |  | [optional]  *isSubscribed* | *bool* |  | [optional]  *lineItems* | xref:ShipmentFeeServiceModel.adoc[*List<ShipmentFeeServiceModel>*] |  | [optional] [default to []]

link:../README.md#documentation-for-models[[Back to Model list\]] link:../README.md#documentation-for-api-endpoints[[Back to API list\]] xref:../README.adoc[[Back to README\]]
