= api_client.api.CarrierQuoteRequestApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:CarrierQuoteRequestApi.md#deleteCarrierQuoteRequest[*deleteCarrierQuoteRequest*]
| *POST* /api/CarrierQuoteRequest/deleteCarrierQuoteRequest
|

| link:CarrierQuoteRequestApi.md#getCarrierQuoteRequest[*getCarrierQuoteRequest*]
| *GET* /api/CarrierQuoteRequest/getCarrierQuoteRequest
|

| link:CarrierQuoteRequestApi.md#getCarrierquoterequests[*getCarrierquoterequests*]
| *POST* /api/CarrierQuoteRequest/getCarrierquoterequests
|

| link:CarrierQuoteRequestApi.md#getPickupAppointment[*getPickupAppointment*]
| *GET* /api/CarrierQuoteRequest/getPickupAppointment
|

| link:CarrierQuoteRequestApi.md#saveAdditionalInformation[*saveAdditionalInformation*]
| *POST* /api/CarrierQuoteRequest/saveAdditionalInformation
|

| link:CarrierQuoteRequestApi.md#saveCarrierQuoteRequest[*saveCarrierQuoteRequest*]
| *POST* /api/CarrierQuoteRequest/saveCarrierQuoteRequest
|

| link:CarrierQuoteRequestApi.md#savePickupAppointment[*savePickupAppointment*]
| *POST* /api/CarrierQuoteRequest/savePickupAppointment
|

| link:CarrierQuoteRequestApi.md#sendCounterOffer[*sendCounterOffer*]
| *POST* /api/CarrierQuoteRequest/sendCounterOffer
|

| link:CarrierQuoteRequestApi.md#sendQuote[*sendQuote*]
| *POST* /api/CarrierQuoteRequest/sendQuote
|
|===

= *deleteCarrierQuoteRequest*

____
CarrierQuoteRequestServiceModel deleteCarrierQuoteRequest(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var id = id_example; // String |

try {
    var result = api_instance.deleteCarrierQuoteRequest(id);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->deleteCarrierQuoteRequest: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:CarrierQuoteRequestServiceModel.adoc[*CarrierQuoteRequestServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getCarrierQuoteRequest*

____
CarrierQuoteRequestServiceModel getCarrierQuoteRequest(id)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var id = id_example; // String |

try {
    var result = api_instance.getCarrierQuoteRequest(id);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->getCarrierQuoteRequest: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *id*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:CarrierQuoteRequestServiceModel.adoc[*CarrierQuoteRequestServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getCarrierquoterequests*

____
QueryResultCarrierQuoteRequestServiceModel getCarrierquoterequests(query)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var query = new Query(); // Query |

try {
    var result = api_instance.getCarrierquoterequests(query);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->getCarrierquoterequests: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *query*
| xref:Query.adoc[*Query*]
|
| [optional]
|===

[discrete]
=== Return type

xref:QueryResultCarrierQuoteRequestServiceModel.adoc[*QueryResultCarrierQuoteRequestServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getPickupAppointment*

____
PickupAppointmentServiceModel getPickupAppointment(carrierQuoteRequestId)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var carrierQuoteRequestId = carrierQuoteRequestId_example; // String |

try {
    var result = api_instance.getPickupAppointment(carrierQuoteRequestId);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->getPickupAppointment: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *carrierQuoteRequestId*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:PickupAppointmentServiceModel.adoc[*PickupAppointmentServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveAdditionalInformation*

____
CarrierQuoteRequestServiceModel saveAdditionalInformation(carrierQuoteRequestId, model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var carrierQuoteRequestId = carrierQuoteRequestId_example; // String |
var model = new CarrierAdditionalInfoServiceModel(); // CarrierAdditionalInfoServiceModel |

try {
    var result = api_instance.saveAdditionalInformation(carrierQuoteRequestId, model);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->saveAdditionalInformation: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *carrierQuoteRequestId*
| *String*
|
| [optional]

| *model*
| xref:CarrierAdditionalInfoServiceModel.adoc[*CarrierAdditionalInfoServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:CarrierQuoteRequestServiceModel.adoc[*CarrierQuoteRequestServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveCarrierQuoteRequest*

____
CarrierQuoteRequestServiceModel saveCarrierQuoteRequest(model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var model = new CarrierQuoteRequestServiceModel(); // CarrierQuoteRequestServiceModel |

try {
    var result = api_instance.saveCarrierQuoteRequest(model);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->saveCarrierQuoteRequest: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *model*
| xref:CarrierQuoteRequestServiceModel.adoc[*CarrierQuoteRequestServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:CarrierQuoteRequestServiceModel.adoc[*CarrierQuoteRequestServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *savePickupAppointment*

____
PickupAppointmentServiceModel savePickupAppointment(carrierQuoteRequestId, model)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var carrierQuoteRequestId = carrierQuoteRequestId_example; // String |
var model = new PickupAppointmentServiceModel(); // PickupAppointmentServiceModel |

try {
    var result = api_instance.savePickupAppointment(carrierQuoteRequestId, model);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->savePickupAppointment: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *carrierQuoteRequestId*
| *String*
|
| [optional]

| *model*
| xref:PickupAppointmentServiceModel.adoc[*PickupAppointmentServiceModel*]
|
| [optional]
|===

[discrete]
=== Return type

xref:PickupAppointmentServiceModel.adoc[*PickupAppointmentServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *sendCounterOffer*

____
ShipmentServiceModel sendCounterOffer(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var request = new CarrierCounterOfferLoadRequest(); // CarrierCounterOfferLoadRequest |

try {
    var result = api_instance.sendCounterOffer(request);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->sendCounterOffer: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:CarrierCounterOfferLoadRequest.adoc[*CarrierCounterOfferLoadRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentServiceModel.adoc[*ShipmentServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *sendQuote*

____
ShipmentServiceModel sendQuote(request)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';
// TODO Configure OAuth2 access token for authorization: oauth2
//api_client.api.Configuration.accessToken = 'YOUR_ACCESS_TOKEN';

var api_instance = new CarrierQuoteRequestApi();
var request = new CarrierApproveLoadRequest(); // CarrierApproveLoadRequest |

try {
    var result = api_instance.sendQuote(request);
    print(result);
} catch (e) {
    print("Exception when calling CarrierQuoteRequestApi->sendQuote: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *request*
| xref:CarrierApproveLoadRequest.adoc[*CarrierApproveLoadRequest*]
|
| [optional]
|===

[discrete]
=== Return type

xref:ShipmentServiceModel.adoc[*ShipmentServiceModel*]

[discrete]
=== Authorization

link:../README.md#oauth2[oauth2]

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
