= api_client.model.CompanyServiceModel

== Load the model package

[source,dart]
----
import 'package:api_client/api.dart';
----

== Properties

Name | Type | Description | Notes -------- | --------- | --------- | --------- *id* | *String* |  | [optional]  *type* | *int* |  | [optional]  *name* | *String* |  | [optional]  *phone* | *String* |  | [optional]  *email* | *String* |  | [optional]  *fax* | *String* |  | [optional]  *address1* | *String* |  | [optional]  *address2* | *String* |  | [optional]  *city* | *String* |  | [optional]  *state* | *String* |  | [optional]  *zip* | *String* |  | [optional]  *scacNumber* | *String* |  | [optional]  *dotNumber* | *String* |  | [optional]  *scacVerified* | *bool* |  | [optional]  *bolPrefix* | *String* |  | [optional]  *isEnabled* | *bool* |  | [optional]  *subdomain* | *String* |  | [optional]  *isaId* | *String* |  | [optional]  *lastUsedBolNumber* | *String* |  | [optional]  *password* | *String* |  | [optional]  *logo* | xref:FileUploadServiceModel.adoc[*FileUploadServiceModel*] |  | [optional]  *label* | *String* |  | [optional]

link:../README.md#documentation-for-models[[Back to Model list\]] link:../README.md#documentation-for-api-endpoints[[Back to API list\]] xref:../README.adoc[[Back to README\]]
