= api_client.api.ConfigApi
:doctype: book

== Load the API package

[source,dart]
----
import 'package:api_client/api.dart';
----

All URIs are relative to _https://localhost_

|===
| Method | HTTP request | Description

| link:ConfigApi.md#explain[*explain*]
| *GET* /api/Config/explain
|

| link:ConfigApi.md#getConfig[*getConfig*]
| *GET* /api/Config/getConfig
|

| link:ConfigApi.md#getConfiguration[*getConfiguration*]
| *POST* /api/Config/getConfiguration
|

| link:ConfigApi.md#saveConfig[*saveConfig*]
| *GET* /api/Config/saveConfig
|
|===

= *explain*

____
String explain(typeName)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new ConfigApi();
var typeName = typeName_example; // String |

try {
    var result = api_instance.explain(typeName);
    print(result);
} catch (e) {
    print("Exception when calling ConfigApi->explain: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *typeName*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

*String*

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getConfig*

____
Object getConfig(typeName)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new ConfigApi();
var typeName = typeName_example; // String |

try {
    var result = api_instance.getConfig(typeName);
    print(result);
} catch (e) {
    print("Exception when calling ConfigApi->getConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *typeName*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:Object.adoc[*Object*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *getConfiguration*

____
ConfigurationServiceModel getConfiguration()
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new ConfigApi();

try {
    var result = api_instance.getConfiguration();
    print(result);
} catch (e) {
    print("Exception when calling ConfigApi->getConfiguration: $e\n");
}
----

[discrete]
=== Parameters

This endpoint does not need any parameter.

[discrete]
=== Return type

xref:ConfigurationServiceModel.adoc[*ConfigurationServiceModel*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: Not defined
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]

= *saveConfig*

____
Object saveConfig(typeName, serializedConfig)
____

[discrete]
=== Example

[source,dart]
----
import 'package:api_client/api.dart';

var api_instance = new ConfigApi();
var typeName = typeName_example; // String |
var serializedConfig = new String(); // String |

try {
    var result = api_instance.saveConfig(typeName, serializedConfig);
    print(result);
} catch (e) {
    print("Exception when calling ConfigApi->saveConfig: $e\n");
}
----

[discrete]
=== Parameters

|===
| Name | Type | Description | Notes

| *typeName*
| *String*
|
| [optional]

| *serializedConfig*
| *String*
|
| [optional]
|===

[discrete]
=== Return type

xref:Object.adoc[*Object*]

[discrete]
=== Authorization

No authorization required

[discrete]
=== HTTP request headers

* *Content-Type*: application/json-patch+json, application/json, text/json, application/_*+json
* *Accept*: Not defined

<<,[Back to top]>> link:../README.md#documentation-for-api-endpoints[[Back to API list\]] link:../README.md#documentation-for-models[[Back to Model list\]] xref:../README.adoc[[Back to README\]]
