= Managing peers
:description: Managing Hyperledger Besu peers

== Limiting peers

Limiting peers reduces the bandwidth used by Hyperledger Besu.
Limiting peers also reduces the CPU time and disk access used to manage and respond to peers.

To reduce the maximum number of peers, use the link:../../Reference/CLI/CLI-Syntax.md#max-peers[`--max-peers`] option.
The default is 25.

== No discovery

To disable P2P peer discovery, use the link:../../Reference/CLI/CLI-Syntax.md#discovery-enabled[`--discovery-enabled`] option.

With discovery disabled, peers that have already discovered or are otherwise configured to connect to the local node (for example, using link:../../Reference/API-Methods.md#admin_addpeer[`admin_addPeer`]) can initiate connections.
xref:Static-Nodes.adoc[Static nodes] can also initiate connections.

== Monitoring peer connections

JSON-RPC API methods to monitor peer connections include:

* link:../../Reference/API-Methods.md#net_peercount[`net_peerCount`]
* link:../../Reference/API-Methods.md#admin_peers[`admin_peers`]
* link:../../Reference/API-Methods.md#debug_metrics[`debug_metrics`].

== Node connections

The default logging configuration does not list node connection and disconnection messages.

To enable listing of node connection and disconnection messages, specify the link:../../Reference/CLI/CLI-Syntax.md#logging[`--logging`] option `--logging=DEBUG`.
For more verbosity, specify `--logging=TRACE`.

The console logs connection and disconnection events when the log level is `DEBUG` or higher.
If the message `+Successfully accepted connection from ...+` displays, connections are getting through the firewalls.

!!!
example "Sample log output"

 `2018-10-16 12:37:35.479-04:00 | nioEventLoopGroup-3-1 | INFO | NettyP2PNetwork | Successfully accepted connection from 0xa979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c`

== Limiting remote connections

In private networks with a level of trust between peers, enabling the link:../../Reference/CLI/CLI-Syntax.md#remote-connections-limit-enabled[remote connection limits] is unnecessary and disabling might increase the speed at which nodes can join the network.
