= Configuring NAT
:description: Configuring NAT with Hyperledger Besu

Use the link:../../Reference/CLI/CLI-Syntax.md#nat-method[`--nat-method`] option to specify the NAT method.
Options are: `UPNP`, `MANUAL`, `DOCKER`, `AUTO`, and `NONE`.

The link:../../Concepts/Node-Keys.md#enode-url[enode] advertised to other nodes during discovery is the external IP address and port.
The link:../../Reference/API-Methods.md#admin_nodeinfo[`admin_nodeInfo`] JSON-RPC API method returns the external address and port for the `enode` and `listenAddr` properties.

While Hyperledger Besu is running, the following are not supported:

* IP address changes
* Changing NAT methods.
To change the NAT method, restart the node with the link:../../Reference/CLI/CLI-Syntax.md#nat-method[`--nat-method`] option set.

== UPnP

Specify `UPNP` to quickly allow inbound peer connections without manual router configuration.
Use UPnP in home or small office environments where a wireless router or modem provides NAT isolation.

UPnP automatically detects if a node is running in a UPnP environment and provides port forwarding.
UPnP might introduce delays during node startup, especially on networks without a UPnP gateway device.

!!!
tip

 UPnP support is often disabled by default in networking firmware. If disabled by default, you
 must explicitly enable UPnP support.

== Manual

Specify `MANUAL` to explicitly configure the external IP address and ports advertised.

By specifying `MANUAL`:

* link:../../Reference/CLI/CLI-Syntax.md#p2p-host[`--p2p-host`] and link:../../Reference/CLI/CLI-Syntax.md#p2p-port[`--p2p-port`] define the advertised host and port for the P2P service.
* link:../../Reference/CLI/CLI-Syntax.md#rpc-http-host[`--rpc-http-host`] and link:../../Reference/CLI/CLI-Syntax.md#rpc-http-port[`rpc-http-port`] define the advertised host and port for the JSON-RPC service.

== Docker

Specify `DOCKER` to explicitly specify Hyperledger Besu is running inside a Docker container.
If you specify `DOCKER`, you advertise the host IP address not the container IP address.

The host IP is the advertised host specified in the https://docs.docker.com/engine/reference/commandline/run/#add-entries-to-container-hosts-file---add-host[`docker run` command].
If not specified in the `docker run` command, the advertised host defaults to the values for link:../../Reference/CLI/CLI-Syntax.md#p2p-host[`--p2p-host`] and link:../../Reference/CLI/CLI-Syntax.md#p2p-port[`--p2p-port`].

== Auto

`AUTO` is the default NAT method.
`AUTO` detects if Besu is running inside Docker container.
If inside a Docker container, `AUTO` acts as if you specified <<docker,`DOCKER`>>.
If not inside a Docker container, `AUTO` acts as if you specified <<none,`NONE`>>.

== None

Specify `NONE` to explicitly specify Besu does not use NAT.
If the NAT method is `NONE`, Besu ignores any values specified in the link:../../Reference/CLI/CLI-Syntax.md#p2p-host[`--p2p-host`], link:../../Reference/CLI/CLI-Syntax.md#p2p-port[`--p2p-port`], link:../../Reference/CLI/CLI-Syntax.md#rpc-http-host[`--rpc-http-host`], and link:../../Reference/CLI/CLI-Syntax.md#rpc-http-port[`--rpc-http-port`] options.
Besu advertises the default values instead.
