= web3.js-eea client library
:description: web3.js-eea client library

The https://github.com/PegaSysEng/eeajs[web3.js-eea library] adds a property to your web3 instance by extending https://github.com/ethereum/web3.js/[web3].
Use the library to create and send RLP-encoded transactions using JSON-RPC.

!!!
note     web3.js-eea supports JSON-RPC over HTTP only.

== Prerequisites

* https://nodejs.org/en/download/[Node.js (version > 10)]

== Add web3.js-eea to project

[source,bash]
----
npm install web3-eea
----

== Initialize EEA client

Initialize your EEA client where:

* `<JSON-RPC HTTP endpoint>` is the JSON-RPC HTTP endpoint of your Hyperledger Besu node.
Specified by the link:../../../Reference/CLI/CLI-Syntax.md#rpc-http-host[`--rpc-http-host`] and link:../../../Reference/CLI/CLI-Syntax.md#rpc-http-port[`--rpc-http-port`] command line options.
* `<chain_id>` is the xref:../../../Concepts/NetworkID-And-ChainID.adoc[chain ID] of your network.

!!!
example

....
```js tab="Syntax"
const EEAClient = require("web3-eea");
const web3 = new EEAClient(new Web3("<JSON-RPC HTTP endpoint>"), <chain_id>);
```

```js tab="Example"
const EEAClient = require("web3-eea");
const web3 = new EEAClient(new Web3("http://localhost:8545"), 2018);
```
....

== Deploying a contract with sendRawTransaction

To deploy a private contract, you need the contract binary.
You can use https://solidity.readthedocs.io/en/develop/using-the-compiler.html[Solidity] to get the contract binary.

!!!
example "Deploying a Contract with sendRawTransaction"

 ```js
 const contractOptions = {
   data: `0x123`, // contract binary
   privateFrom: "orionNode1PublicKey",
   privateFor: ["orionNode3PublicKey"],
   privateKey: "besuNode1PrivateKey"
 };
 return web3.eea.sendRawTransaction(contractOptions);
 ```

`web3.eea.sendRawTransaction(contractOptions)` returns the transaction hash.
To get the private transaction receipt, use `web3.eea.getTransactionReceipt(txHash)`.

== web3.js-eea methods

For more information about the web3.js-eea methods, see the xref:../../../Reference/web3js-eea-Methods.adoc[web3.js-eea reference documentation].
