= Access the Hyperledger Besu API
:description: Hyperledger Besu API

Access the xref:../../../Reference/API-Methods.adoc[Hyperledger Besu API] using:

* xref:Using-JSON-RPC-API.adoc[JSON-RPC over HTTP or WebSockets]
* xref:RPC-PubSub.adoc[RPC Pub/Sub over WebSockets]
* xref:GraphQL.adoc[GraphQL over HTTP].

The following sections provide information about JSON-RPC, RPC Pub/Sub, and GraphQL.

== Enabling API access

To enable API access, use the link:../../../Reference/CLI/CLI-Syntax.md#rpc-http-enabled[`--rpc-http-enabled`], link:../../../Reference/CLI/CLI-Syntax.md#rpc-ws-enabled[`--ws-http-enabled`], and link:../../../Reference/CLI/CLI-Syntax.md#graphql-http-enabled[`--graphql-http-enabled`] options.

== Service hosts

To specify the host the API service listens on, use the link:../../../Reference/CLI/CLI-Syntax.md#rpc-http-host[`--rpc-http-host`], link:../../../Reference/CLI/CLI-Syntax.md#rpc-ws-host[`--rpc-ws-host`], and link:../../../Reference/CLI/CLI-Syntax.md#graphql-http-host[`--graphql-http-host`] options.
The default host is `127.0.0.1`.

To allow remote connections, set the host to `0.0.0.0`.

!!!
caution

 Setting the host to `0.0.0.0` exposes the API service connection on your node to any remote
 connection. In a production environment, ensure you use a firewall to avoid exposing your node
 to the internet.

== Service ports

To specify the port the API service listens on, use the link:../../../Reference/CLI/CLI-Syntax.md#rpc-http-port[`--rpc-http-port`], link:../../../Reference/CLI/CLI-Syntax.md#rpc-ws-port[`--rpc-ws-port`], and link:../../../Reference/CLI/CLI-Syntax.md#graphql-http-port[`--graphql-http-port`] options.

The default ports are:

* 8545 for JSON-RPC over HTTP
* 8546 for JSON-RPC over WebSockets
* 8547 for GraphQL over HTTP.

Ports must be link:../../Find-and-Connect/Managing-Peers.md#port-configuration[exposed appropriately].

== Host whitelist

To prevent DNS rebinding, Besu accepts incoming HTTP requests, WebSockets connections, and GraphQL requests only from hostnames specified using the link:../../../Reference/CLI/CLI-Syntax.md#host-whitelist[`--host-whitelist`] option.
Besu accepts incoming requests and connections from `localhost` and `127.0.0.1` by default.

If your application publishes RPC ports, specify the hostnames when starting Besu.

!!!
example

 ```bash
 besu --host-whitelist=example.com
 ```

Specify "*" for `--host-whitelist` to effectively disable host protection.

!!!
caution

 Specifying "*" for `--host-whitelist` is not recommended for production code.

== Not supported by Besu

=== Account management

Account management relies on private key management in the client, which is not supported by Besu.

To send signed transactions, use link:../../../Reference/API-Methods.md#eth_sendrawtransaction[`eth_sendRawTransaction`].
`eth_sendTransaction` is not implemented.

For xref:../../Send-Transactions/Account-Management.adoc[account management], use third-party wallets.

=== Protocols

Besu does not implement the Whisper and Swarm protocols.
