:doctype: book

description: How to trace transactions
// - END of page meta data

= Trace Transactions

Use the link:../../Reference/API-Methods.md#trace-methods[`TRACE` API] to get detailed information about  transaction processing.
Enable the link:../../Reference/API-Methods.md#trace-methods[`TRACE` API] using  the link:../../Reference/CLI/CLI-Syntax.md#rpc-http-api[`-rpc-http-api`] or link:../../Reference/CLI/CLI-Syntax.md#rpc-ws-api[`rpc-ws-api`]  command line options.

Use the link:../../Reference/API-Methods.md#trace_replayblocktransactions[`trace_replayBlockTransactions`]  JSON RPC API method and specify the trace types required.
Options are xref:../../Concepts/Transactions/Trace-Types.adoc[`trace`, `vmTrace`, or `stateDiff`].

Your node must be an archive node (that is, synchronised without pruning or fast sync) or the requested block must be within the last 1024 blocks.

!!!
important +     The `TRACE` API is an early access feature in 1.4.
The return values may change between v1.4 and     v1.5.
