:doctype: book

description: Methods for accessing and managing private transactions and privacy groups with Hyperledger Besu
// - END of page meta data

= Accessing Private and Privacy Marker Transactions

A Hyperledger Besu private transaction creates a xref:../../Concepts/Privacy/Private-Transaction-Processing.adoc[privacy marker transaction] in addition to the private transaction itself.

== Transaction Receipts

With the transaction hash returned when submitting the private transaction, use:

* link:../../Reference/API-Methods.md#eth_gettransactionreceipt[`eth_getTransactionReceipt`] to get the transaction receipt for the  privacy marker transaction.
* link:../../Reference/API-Methods.md#priv_gettransactionreceipt[`priv_getTransactionReceipt`] to get the transaction receipt for the private transaction.

The transaction receipt includes a `status` indicating success (`0x1`) or failure (`0x0`) of the transactions.

!!!
example "Example Private Transaction Failure"     A transaction is submitted using xref:../Send-Transactions/Creating-Sending-Private-Transactions.adoc[`eea_sendRawTransaction`]      to deploy a private contract.
If the contract deployment fails due to insufficient gas, the privacy marker transaction receipt      has a status of success and the private transaction receipt has a status of failure.

== Transactions

With the transaction hash returned when submitting the private transaction, use:

* link:../../Reference/API-Methods.md#eth_gettransactionbyhash[`eth_getTransactionByHash`] to  get the Privacy Marker Transaction .
* link:../../Reference/API-Methods.md#priv_getprivatetransaction[`priv_getPrivateTransaction`]  to get the private transaction.
